---
- name: Determine bridge name
  set_fact:
    bridge: "{{ (all_links | selectattr('a', 'in', [node_a, node_b]) | selectattr('b', 'in', [node_a, node_b]) | first).bridge }}"

- name: Bring link up
  command: "ip link set {{ bridge }} up"
