---
- name: Destroy all VMs
  hosts: hypervisor
  gather_facts: no
  become: yes
  roles:
    - role: vm-provision
      tasks_from: destroy-vm

- name: Remove L1 fabric
  hosts: hypervisor
  gather_facts: no
  become: yes
  roles:
    - role: l1-fabric
      tasks_from: destroy
