---
- name: Set fabric bridges down
  command: ip link set {{ item.bridge }} down
  loop: "{{ all_links }}"
  ignore_errors: yes

- name: Delete fabric bridges
  command: ip link delete {{ item.bridge }}
  loop: "{{ all_links }}"
  ignore_errors: yes

- name: Set management bridge down
  command: ip link set {{ mgmt_bridge }} down
  ignore_errors: yes

- name: Delete management bridge
  command: ip link delete {{ mgmt_bridge }}
  ignore_errors: yes
