---
- include_tasks: bastion.yml
  when: role == 'bastion'
- include_tasks: services.yml
  when: role == 'services'
- include_tasks: orchestrator.yml
  when: role == 'orchestrator'
- include_tasks: telemetry.yml
  when: role == 'telemetry'
- include_tasks: registry.yml
  when: role == 'registry'
