---
- name: Install dnsmasq via dnf
  dnf:
    name: dnsmasq
    state: present

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Enable systemd-resolved override
  file:
    path: /etc/resolv.conf
    state: absent
- copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 127.0.0.1
      search themis.local

- name: Start dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
